const app=document.querySelector('#app'),bar=document.querySelector('#bar');let step=0;const total=11;
const go=(html,n=step)=>{step=n;bar.style.width=(step/total*100)+'%';app.innerHTML=`<section class="screen"><div class="card">${html}</div></section>`;scrollTo(0,0)};
const btn=(t,fn='next()')=>`<button class="btn" onclick="${fn}">${t}</button>`;
function next(){step++;render()}
function render(){
if(step===0)go(`<div class="eyebrow">TOP SECRET • FOR ONE BRIAN MATTHEW ONLY</div><h1 class="big">A Very Important Quest</h1><p class="lead">Brian Matthew, you have been selected for a highly important mission.<br><br>There is something waiting for you at the end.<br>Unfortunately, I have decided you must work for it.</p>${btn('BEGIN →')}<p class="tiny">Estimated difficulty: concerning. Estimated torso length: short.</p>`,0);
else if(step===1)go(`<div class="chapter">Prologue</div><h2 class="big">Once upon a time…</h2><p class="lead">There was a boy named Brian. He loved God, Macbeth, How to Train Your Dragon, music, and—somewhat alarmingly—identifying Honda Civics from great distances.</p><p class="lead">Then, through church, university, youth ministry, and a truly unreasonable number of hour-long commutes… he became friends with a girl named Joey.</p>${btn('this sounds suspicious →')}`);
else if(step===2)go(`<div class="chapter">Chapter I</div><h2 class="big">The Commute Era</h2><p class="quote">Somehow, an hour travelling home never felt like an hour when I was talking to you.</p><p class="lead">We were friends first. We served together. We talked and talked and talked. And somewhere in all that ordinary time, you became very important to me.</p>${btn('continue the investigation →')}`);
else if(step===3)go(`<div class="chapter">Chapter II</div><h2 class="big">The Fiji Incident</h2><img class="photo" src="plane.jpg"><p class="lead">One night in Fiji, Joey was stuck on a bus. Joey was thirsty. There was no water left.</p><p class="lead"><b>Mission parameters:</b> impossible.</p><p class="lead">And then suddenly there was a water bottle in my hand, because you had literally climbed over people to get one to me.</p><p class="quote">I still think about that.</p>${btn('water acquired ✓ →')}`);
else if(step===4)go(`<div class="chapter">Chapter III</div><h2 class="big">Brian Identification Test</h2><p class="lead">A yellow Honda Civic has been spotted. What is the correct response?</p><div><button class="choice" onclick="wrong('Ignore it? Are you Brian Matthew at all?')">Ignore it</button><button class="choice" onclick="wrong('Respectfully, no.')">Say “nice car”</button><button class="choice" onclick="next()">POINT IT OUT + PUNCH JOEY</button></div><img class="photo civic" src="yellow-civic.jpg">`);
else if(step===5)go(`<div class="chapter">Chapter IV</div><h2 class="big">The Archives</h2><div class="polaroids"><figure style="--r:-2deg"><img src="creme-1.jpg"><figcaption>making things together ♡</figcaption></figure><figure style="--r:2deg"><img src="creme-2.jpg"><figcaption>brimmy + joey</figcaption></figure><figure style="--r:-1deg"><img src="beach.jpg"><figcaption>adventures with you</figcaption></figure><figure style="--r:2deg"><img src="sunset.jpg"><figcaption>Fiji, us, and a very good sky</figcaption></figure></div>${btn('there is more →')}`);
else if(step===6)go(`<div class="chapter">Chapter V</div><h2 class="big">A Familiar Challenge</h2><p class="lead">Brian felt a strange sense of déjà vu. Somewhere, a Codex Wheel turned. Somewhere else, Macbeth stared intensely at a dagger.</p><div class="cipher">GPSUJTTJTJNP</div><p class="lead">Caesar has moved every letter forward by one. Move them back.</p><input id="answer" class="input" placeholder="your answer"><br>${btn('SUBMIT','checkCipher()')}<p id="hint" class="tiny">Hint: it is something we are looking forward to.</p>`);
else if(step===7)go(`<div class="chapter">Chapter VI</div><h2 class="big">Choose Wisely.</h2><p class="lead">Joey has had A Day™. Brian encounters her. What does he do?</p><button class="choice" onclick="sweet('Correct. +100 boyfriend points.')">give hug</button><button class="choice" onclick="sweet('Food is an excellent tactical decision.')">bring food</button><button class="choice" onclick="sweet('You listen to me so well. Correct.')">listen to the entire rant</button><button class="choice" onclick="badEnd()">run away</button><p id="response" class="lead"></p>`);
else if(step===8)go(`<div class="chapter">Chapter VII</div><h2 class="big">Meadows</h2><img class="photo" src="shadows.jpg"><p class="lead">I loved lying on the grass at Gardens by the Bay and just talking with you. I love that some of my favourite moments with you aren't complicated at all.</p><p class="quote">It's just us, somewhere, with time to talk.</p>${btn('keep going →')}`);
else if(step===9)go(`<div class="chapter">Chapter VIII</div><h2 class="big">Things I Keep</h2><p class="love-line" style="animation-delay:.1s">I love how incredibly loving you are to me.</p><p class="love-line" style="animation-delay:.8s">I love your heart for God.</p><p class="love-line" style="animation-delay:1.5s">I love that we don't only get to be together — we get to serve together.</p><p class="love-line" style="animation-delay:2.2s">I love listening to you make music out of nothing.</p><p class="love-line" style="animation-delay:2.9s">I love the big adventures and the hour-long commutes.</p><p class="love-line" style="animation-delay:3.6s">I love doing life with you, Brimmy.</p><div style="margin-top:60px"><button class="btn" id="final-chapter-btn">one last thing →</button></div>`);
else if(step===10)go(`<div class="eyebrow">FINAL CHAPTER</div><h2 class="big">There was never really a quest.</h2><p class="lead">You didn't actually need to solve anything.</p><p class="lead">I just wanted to take you through these little pieces of us, because somewhere between serving together, long commutes, Fiji, music shops, meadows, yellow cars, and everything else…</p><p class="quote">you became one of my favourite parts of my story.</p><p class="lead">And there is really only one thing I made this whole website to tell you.</p>${btn('tell me','finale()')}`);
}
function wrong(t){alert(t+'\n\nTry again, Brimmy.');}function sweet(t){document.querySelector('#response').textContent=t;setTimeout(next,900)}function badEnd(){go(`<div class="bad" style="padding:60px;border-radius:8px"><div class="eyebrow">BAD ENDING</div><h2 class="big">Brian was never seen again.</h2><p class="lead">An avoidable tragedy.</p>${btn('perhaps reconsider','step=7;render()')}</div>`,7)}function checkCipher(){let a=document.querySelector('#answer').value.toLowerCase().replace(/[^a-z]/g,'');if(a==='fortississimo'){next()}else{document.querySelector('#hint').textContent='Not quite. Shift each letter BACK one. GPSUJTTJTJNP → ?'}}
document.addEventListener('click',function(e){if(e.target && e.target.id==='final-chapter-btn'){step=10;render();}});
function finale(){document.body.classList.add('final');go(`<div class="heart">♥</div><div class="eyebrow">FOR BRIAN MATTHEW, FROM JOEY</div><h1 class="big">I love you,<br>Brian Matthew.</h1><p class="lead">Very, very much.<br><br>Thank you for being my Brimmy.</p><div class="polaroids"><figure style="--r:-2deg"><img src="creme-2.jpg"><figcaption>us ♡</figcaption></figure><figure style="--r:2deg"><img src="sunset.jpg"><figcaption>and many more adventures to come</figcaption></figure></div><p class="tiny">P.S. your torso is still short.</p>`,11);for(let i=0;i<55;i++){setTimeout(()=>{let x=document.createElement('div');x.className='confetti';x.textContent=['♥','✦','♡','♪'][Math.floor(Math.random()*4)];x.style.left=Math.random()*100+'vw';x.style.animationDuration=(2+Math.random()*3)+'s';document.body.appendChild(x);setTimeout(()=>x.remove(),5000)},i*45)}}render();